# Homework 20

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sy
import utils as utils
from fractions import Fraction
from sklearn.metrics import pairwise_distances

from IPython.display import display, HTML

# Inline plotting
%matplotlib inline

# Make sympy print pretty math expressions
sy.init_printing()

utils.load_custom_styles()

---
## Exercise 4.1

<img src="figures/homework-20/exercise-4.1.png" width="600" />




















---
## Exercise 4.2

<img src="figures/homework-20/exercise-4.2.png" width="600" />




















In [2]:
c1 = np.array([[-1,  0, -0.5, -1.5, -2,  0, -1  ],
               [ 0, -1, -0.5, -1.5,  0, -2, -1.3]])

c2 = np.array([[ 1, 1.3, 0.7, 2.5, 0],
               [ 1, 0.7, 1.3,   1, 1]])

X = np.array([[0, 1, -1,  0.7, -0.2],
              [0, 1,  0, -0.2,  1.5]])

### Nearest Class Centroid classifier

Nearest Class Centroid represents each class $c_k$ with the corresponding mean class vector:

<img src="figures/lecture-19/ncc-class-representation.png" width="600" />


Given the class mean vectors $\mu_1, \mu_2, \cdots, \mu_K$, the new sample $\mathbf{x}_{*}$ is classified to the class $c_k$ corresponding to the
smallest distance:

<img src="figures/lecture-19/ncc-classification-of-new-sample.png" width="600" />





In [3]:
m1 = np.mean(c1, axis=1).reshape(-1, 1)
m2 = np.mean(c2, axis=1).reshape(-1, 1)

In [4]:
m1

array([[-0.85714286],
       [-0.9       ]])

In [5]:
m2

array([[1.1],
       [1. ]])

In [6]:
combined_vectors = np.concatenate([X, m1, m2], axis=1)
combined_vectors

array([[ 0.        ,  1.        , -1.        ,  0.7       , -0.2       ,
        -0.85714286,  1.1       ],
       [ 0.        ,  1.        ,  0.        , -0.2       ,  1.5       ,
        -0.9       ,  1.        ]])

In [7]:
# Compute distances between samples and m_k's
dist = pairwise_distances(combined_vectors.T)

N = X.shape[1]

# Remove the top N rows
dist = np.delete(dist, np.s_[0:N], axis=0)

# Remove the last two columns
dist = np.delete(dist, np.s_[N:N+2], axis=1)

dist

array([[1.24285714, 2.65687403, 0.91126734, 1.70724746, 2.48834016],
       [1.48660687, 0.1       , 2.32594067, 1.26491106, 1.39283883]])

In [8]:
# Classify based on minimum distance
np.argmin(dist, axis=0)+1

array([1, 2, 1, 2, 2])

So the Nearest Centroid Classification is as follows:
\begin{align}
c_1 &= \{ \mathbf{x}_1, \mathbf{x}_3 \} \\
c_2 &= \{ \mathbf{x}_2, \mathbf{x}_4, \mathbf{x}_5  \} \\
\end{align}

### Nearest Neighbour

In [9]:
def compute_min_distances(X, c):
    N = X.shape[1]
    N_c = c.shape[1]
    combined_vectors = np.concatenate([X, c], axis=1)
    dist = pairwise_distances(combined_vectors.T)
    dist = np.delete(dist, np.s_[0:N], axis=0)
    dist = np.delete(dist, np.s_[N:N+N_c], axis=1)
    return np.min(dist, axis=0)

In [10]:
dist_c1 = compute_min_distances(X, c1)
dist_c2 = compute_min_distances(X, c2)
dist = np.concatenate([[dist_c1], [dist_c2]], axis=0)
dist

array([[0.70710678, 2.12132034, 0.        , 1.06301458, 1.7       ],
       [1.        , 0.        , 1.41421356, 1.08166538, 0.53851648]])

In [11]:
# Classify based on minimum distance
np.argmin(dist, axis=0)+1

array([1, 2, 1, 1, 2])

Nearest Neighbour Classification is as follows:
\begin{align}
c_1 &= \{ \mathbf{x}_1, \mathbf{x}_3, \mathbf{x}_4  \} \\
c_2 &= \{ \mathbf{x}_2,  \mathbf{x}_5  \} \\
\end{align}

---
## Exercise 4.3

<img src="figures/homework-20/exercise-4.3.png" width="600" />




















---
## Exercise 4.4

<img src="figures/homework-20/exercise-4.4a.png" width="600" />




















<img src="figures/homework-20/exercise-4.4b.png" width="600" />


















