## Lecture 6: Solving Linear Equations

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sy
import fractions
import utils as utils

from func import Func
from linalg import LinearSystem

# Inline plotting
%matplotlib inline

# Make sympy print pretty math expressions
sy.init_printing()

Systems of linear equations have the following form: $A \boldsymbol{x} = b$ where $A$ is an $m \times n$ matrix, $m \geq n$, $x \in \mathbb{R}^n$, $b \in \mathbb{R}^m$ and the rank$(A)=n$.



---
## Matrix Norms and Condition Numbers




<img src="figures/lecture-06/matrix-norms-and-condition-numbers.png" width="600" />


### Matrix Norms

<img src="figures/lecture-06/matrix-norms.png" width="600" />






The Frobenius norm simply squares each entry in the matrix, sum them together and takes the square root of the sum.:

<img src="figures/lecture-06/frobenius-norm-example.png" width="600" />


In [2]:
A = [[4, 2],
     [0, 4]]
# Compute the Frobenius matrix norm
np.linalg.norm(A, ord='fro')

The Frobenius norm is not always useful. We will use two **subordinate matrix norms** that are easy to compute:

<img src="figures/lecture-06/theorem-matrix-norms.png" width="600" />


In [3]:
A = [[ -3,  2,   4,  -3],
     [  5, -2,  -3,   5],
     [  2,  1,  -6,   4],
     [  1,  1,   1,   1]]

In [4]:
# Compute the first order matrix norm
# max(sum(abs(x), axis=0))
np.linalg.norm(A, ord=1)

In [5]:
# Compute the infinite matrix norm
# max(sum(abs(x), axis=1))
np.linalg.norm(A, ord=np.inf)

In [6]:
# Compute the second matrix norm i.e. largest sing. value
np.linalg.norm(A, ord=2)

### Condition Numbers

Matrix Norms can be used to estimate the sensitivity of linear systems to small changes in the coefficient matrix $A$. Consider the following example:

<img src="figures/lecture-06/condition-number-example.png" width="600" />




<img src="figures/lecture-06/definition-conditioned.png" width="600" />






<img src="figures/lecture-06/well-conditioned-matrix-meaning.png" width="600" />


<img src="figures/lecture-06/errors.png" width="600" />


The **residual** or the error is represented by the vector $r$:
$$
r =  b - b' = b - Ax'
$$

The **relative residual** is defined as follows:
$$
\frac{\lVert  b- Ax' \rVert}{\lVert b \rVert} = \frac{\lVert r \rVert}{\lVert b \rVert}
$$

In [19]:
A = [[3, 2],
     [1, 1]]
b = [5, 2]
linsys = LinearSystem(A, b)
linsys.relative_residual([1.1, 0.88])

<img src="figures/lecture-06/relative-error-estimation.png" width="600" />


<img src="figures/lecture-06/len-r-div-len-a.png" width="200" />


<img src="figures/lecture-06/norm-b-div-norm-a.png" width="200" />


<img src="figures/lecture-06/derive-condition-number.png" width="400" />


<img src="figures/lecture-06/definition-condition-number.png" width="600" />


---
## Consistency

If $\boldsymbol{b}$ does not belong to the range of $A$ then the system is said to be **inconsistent**. We can determine if a system is inconsistent if the rank $A < $ rank $[A|b]$.

The range (aka. image or column space) of a matrix is the the span (set of all possible linear combinations) of its column vectors.


In [20]:
A = [[3, 2],
     [1, 1]]
b = [5, 2]
linsys = LinearSystem(A, b)

In [8]:
linsys.is_inconsistent()

False

In [9]:
linsys.least_squares_solution()

array([[1],
       [1]])

In [10]:
linsys.relative_residual([1, 1])

---
## Solving Linear Systems

Let $x^{*}$ be a vector that minimises the squared sum of residuals $\lVert Ax - b \rVert^2$ i.e., for all $x \in \mathbb{R}^n$,

\begin{align}
\lVert Ax - b \rVert^2 \geq \lVert A x^{*} - b \rVert^2
\end{align}

We says that the vector $x^{*}$ is the **least-squares solution** to the linear system $Ax = b$.

<img src="figures/lecture-06/theorem-least-squares-solution.png" width="600" />

<img src="figures/lecture-06/least-squares-solution-derivation.png" width="600" />


There is a geometric interpretation of least-squares solution:

<img src="figures/lecture-06/least-squares-solution-geometric.png" width="600" />


---
## Least-Squares Problems

<img src="figures/lecture-06/example-12.1.png" width="600" />



Suppose $x_1$ represent the first type of concrete and $x_2$ represent the second. This problem can be formulated with the following linear equations:

$$
0.3 x_1 + 0.1 x_2 = 5 \\
0.4 x_1 + 0.2 x_2 = 3 \\
0.3 x_1 + 0.7 x_2 = 4
$$

In [11]:
def create_ex121():
    A = [[0.3, 0.1],
         [0.4, 0.2],
         [0.3, 0.7]]
    b = [5, 3, 4]
    return LinearSystem(A, b)
ex121 = create_ex121()
sol121 = ex121.least_squares_solution()
sol121

array([[2145/203],
       [195/203]])

In [12]:
utils.to_decimal(sol121)

---

## Example 12.1: Line Fitting

The least-squares analysis can also be used to find a straight line that best fit a set of experimental data. This is a useful tool that can be used when a system of equations is inconsistent. Suppose we have a problem that can represented as a set of three linear equations:
\begin{align}
3m + c &= 3 \\
3m + c &= 4 \\
4m + c &= 15
\end{align}
We would like to find a straight line given by:
\begin{align}
y = mt + c
\end{align}
The straight line that best fit the data points is the one that minimises:
$$
\lVert Ax - b \rVert^2
$$
Therefore, we can use least-squares solution on this problem.

In [13]:
def create_ex123():
    A = [[2, 1],
         [3, 1],
         [4, 1]]
    b = [3, 4, 15]
    return LinearSystem(A, b)
ex122 = create_ex123()

In [14]:
# Check whether the system is inconsistent
ex122.is_inconsistent()

True

In [15]:
ex122.least_squares_solution()

array([[6],
       [-32/3]])

Using the least-squares solution, we have found that the line that best fit the data points is described by:

\begin{align}
 y = 6t - \frac{32}{3}
\end{align}

A graphical illustration of our problem is shown in Figure 12.2:

<img src="figures/lecture-06/figure-12.2.png" width="600" />


---
## Recursive Least-Squares (RLS) Algorithm

In Example 12.1, we are given a set of experimental points $\{ (t_0, y_0), (t_1, y_1), (t_2, y_2) \}$, and we find the parameters $m^{*}$ and $c^{*}$ of the straight line that best fits these data in the least-squares sense. Suppose that
we are now given an extra measurement point $(t_3, y_3)$, so that we now have a  set of four experimental data points. We need to update our line. There is two ways to solve this:

1. We can go through the procedure for finding the parameters of the line of best fit for this set of four points. 
2. We can use previous calculations of $m^{*}$ and $c^{*}$ for the three data points to calculate the parameters for the four data points. This is more efficient. In effect, we simply "update" our values of $m^{*}$ and $c^{*}$ to accommodate the new data point. 

The second procedure is called the recursive least-squares (RLS) algorithm.


<img src="figures/lecture-06/derive-rls-1.png" width="600" />




<img src="figures/lecture-06/derive-rls-2.png" width="600" />




<img src="figures/lecture-06/derive-rls-3.png" width="600" />




<img src="figures/lecture-06/derive-rls-4.png" width="600" />




<img src="figures/lecture-06/derive-rls-5.png" width="600" />




<img src="figures/lecture-06/derive-rls-6.png" width="600" />



where

<img src="figures/lecture-06/derive-rls-8.png" width="200" />




<img src="figures/lecture-06/derive-rls-7.png" width="600" />



--- 
## Example 12.6

<img src="figures/lecture-06/example-12.6-a.png" width="600" />




<img src="figures/lecture-06/example-12.6-b.png" width="600" />



<img src="figures/lecture-06/example-12.6-c.png" width="600" />



<img src="figures/lecture-06/example-12.6-d.png" width="600" />


---
## Solution to a Linear System with Minimum Norm


<img src="figures/lecture-06/linear-system-with-minimum-norm-problem.png" width="600" />




<img src="figures/lecture-06/linear-system-with-minimum-norm-solution.png" width="600" />



---
## Example 12.7

<img src="figures/lecture-06/example-12.7.png" width="600" />




In [16]:
def create_ex127():
    A = [[1, 2, -1],
         [4, 1,  3]]
    b = [1, 0]
    return LinearSystem(A, b)
ex127 = create_ex127()

In [17]:
solution127 = ex127.solve_minimum_norm()
solution127

array([[2/21],
       [1/3],
       [-5/21]])

In [18]:
utils.to_decimal(solution127)

---

## Kaczmarz's Algorithm


<img src="figures/lecture-06/kaczmarz-algorithm-intro.png" width="600" />


<img src="figures/lecture-06/kaczmarz-algorithm-1.png" width="600" />


<img src="figures/lecture-06/kaczmarz-algorithm-2.png" width="600" />


<img src="figures/lecture-06/kaczmarz-algorithm-3.png" width="600" />


<img src="figures/lecture-06/kaczmarz-convergence-theorem.png" width="600" />




---

## Moore-Penrose inverse




The Moore-Penrose inverse defines *pseudoinverse* or *generalised inverse* of a given matrix $A \in \mathbb{R}^{m \times n}$ which plays the role as $A^{-1}$ when $A$ does not have an inverse (e.g., when $A$ is not a square matrix). The Moore-Pensore inverse of a given matrix $A$ is denoted $A^{\dagger}$


<img src="figures/lecture-06/moore-penrose-inverse-problem.png" width="600" />

where $r \leq \min\{m,n\}$.

<img src="figures/lecture-06/moore-penrose-inverse-case-1.png" width="600" />


<img src="figures/lecture-06/moore-penrose-inverse-case-2.png" width="600" />
