## Lecture 6: Solving Linear Equations

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sympy as sy
import fractions
import utils as utils

from func import Func
from linalg import LinearSystem

# Inline plotting
%matplotlib inline

# Make sympy print pretty math expressions
sy.init_printing()

Systems of linear equations have the following form:
$$
A \boldsymbol{x} = \boldsymbol{b}
$$
where $A$ is an $m \times n$ matrix, $m \geq n$, $x \in \mathbb{R}^n$, $b \in \mathbb{R}^m$.

Typically, we are given $A$ and $b$ and we are asked to find $x$. For small matrix $A$ and $b$, we can solve it using Gaussian Elimination by creating a tableau and reducing the tableau to Reduced Row Echelon Form. From a computational point of view Gaussian Elimination is useful for small and large systems of linear equations. The problem with Gaussian Elimination is that we can not iteratively find a better and better solution. Instead, it finds the final solution. In the following lectures, we will talk about finding approximate solutions. An iterative approach can be useful if you have say have one million variables.

The system $Ax=b$ is called a homogenous system if $b=0$ i.e., $Ax=0$. 

---
## Matrix Norms and Condition Numbers




<img src="figures/lecture-06/matrix-norms-and-condition-numbers.png" width="600" />


## Matrix Norms

There are many different norms like the infinity norm:

<img src="figures/lecture-06/matrix-norms.png" width="600" />






The Frobenius norm simply squares each entry in the matrix, sum them together and takes the square root of the sum.:

<img src="figures/lecture-06/frobenius-norm-example.png" width="600" />


In [2]:
A = [[4, 2],
     [0, 4]]
# Compute the Frobenius matrix norm
np.linalg.norm(A, ord='fro')

The Frobenius norm is not always useful. We will use two **subordinate matrix norms** that are easy to compute:

<img src="figures/lecture-06/theorem-matrix-norms.png" width="600" />


In [3]:
A = [[ -3,  2,   4,  -3],
     [  5, -2,  -3,   5],
     [  2,  1,  -6,   4],
     [  1,  1,   1,   1]]

In [4]:
# Compute the first order matrix norm
# max(sum(abs(x), axis=0))
np.linalg.norm(A, ord=1)

In [5]:
# Compute the infinite matrix norm
# max(sum(abs(x), axis=1))
np.linalg.norm(A, ord=np.inf)

In [6]:
# Compute the second matrix norm i.e. largest sing. value
np.linalg.norm(A, ord=2)

### Condition Numbers

A condition number can be used to estimate the sensitivity of linear systems to small changes in the coefficient matrix $A$.

In the following example, we look at one system (5) that we want to represent in a computer. Assume that for some reason, we are only able to represent numbers with 3 decimal places. In such case, the representation in our computer looks like the system in (6). Notice the only difference is the coefficient $a_{22}$. If we compute the solution in the computer, we get $x' = [2, 1]^T$ whereas the exact solution is $x=[1, 2]^T$. These are two different numbers.

If you plot the two equations in the system then we would get something like this:

<img src="figures/lecture-06/ill-conditioned-geometric.png" width="400" />

Plotting the equations, we observe that the lines corresponding to the equations are very close at being parallel. So when we  make a small change in the coefficients, one of the lines is moved slightly. Since the lines are very close to one another, the intersection point (i.e., the solution) will change significantly. 

To summarise: if the lines are close to being parallel, we get into a situation where we get very different solutions to solving two systems with small change in the coefficient. 

So the **condition number** tell us something about whether the solution that the computer calculates is close to the real solution. 

Consider the following example:

<img src="figures/lecture-06/condition-number-example.png" width="600" />




<img src="figures/lecture-06/definition-conditioned.png" width="600" />






<img src="figures/lecture-06/well-conditioned-matrix-meaning.png" width="600" />


<img src="figures/lecture-06/errors.png" width="600" />


### Derivation of the Condition Number

We want the relative error to be small. But we don't know what the true $x$ is. Therefore, we need another quantity.

The **residual** or the error is represented by the vector $r$:
$$
r =  b - b' = b - Ax'
$$

The **relative residual** is defined as follows:
$$
\frac{\lVert  b- Ax' \rVert}{\lVert b \rVert} = \frac{\lVert r \rVert}{\lVert b \rVert}
$$

In [7]:
A = [[3, 2],
     [1, 1]]
b = [5, 2]
linsys = LinearSystem(A, b)
linsys.relative_residual([1.1, 0.88])

In [8]:
linsys.condition_number()

<img src="figures/lecture-06/relative-error-estimation.png" width="600" />


Normally, we cannot calculate the relative error since we don't know what $x$ is. Instead, we use the **relative residual** to derive the condition number.

<img src="figures/lecture-06/len-r-div-len-a.png" width="200" />


<img src="figures/lecture-06/norm-b-div-norm-a.png" width="200" />


<img src="figures/lecture-06/derive-condition-number.png" width="400" />


<img src="figures/lecture-06/definition-condition-number.png" width="600" />


Condition Number tells us how bad a matrix is. This number is very high if the matrix is very close of being singular i.e., the matrix cannot be inverted. Geometrically, this means that the lines defined by the matrix is very close to being parallel.

---
### Exercise during the Lecture




<img src="figures/lecture-06/lecture-exercise.png" width="600" />


In [9]:
A = [[3, 2],
     [1, 1]]
b = [5, 2]
x_prime = [1.1, 0.88]

A_norm = np.linalg.norm(A, ord=np.inf)
A_inv_norm = np.linalg.norm(np.linalg.inv(A), ord=np.inf)
cond_inf = A_norm * A_inv_norm
cond_inf

In [10]:
b_prime = np.array(A) @ x_prime
b_prime

array([253/50, 99/50])

In [11]:
r = b - b_prime
r

array([-3/50, 1/50])

In [12]:
lower_bound = (1/cond_inf) * (np.linalg.norm(r, np.inf) / np.linalg.norm(b, np.inf))
lower_bound

In [13]:
upper_bound = (cond_inf) * (np.linalg.norm(r, np.inf) / np.linalg.norm(b, np.inf))
upper_bound

In [14]:
x = np.array([1, 1])
e = x - x_prime
e

array([-1/10, 3/25])

In [15]:
relative_error = np.linalg.norm(e, np.inf) / np.linalg.norm(x, np.inf)
relative_error

---
## Consistency

If $\boldsymbol{b}$ does not belong to the range of $A$ then the system is said to be **inconsistent**. We can determine if a system is inconsistent if the rank $A < $ rank $[A|b]$.

The range (aka. image or column space) of a matrix is the the span (set of all possible linear combinations) of its column vectors.


In [16]:
A = [[3, 2],
     [1, 1]]
b = [5, 2]
linsys = LinearSystem(A, b)

In [17]:
linsys.is_inconsistent()

False

In [18]:
linsys.least_squares_solution()

array([[1],
       [1]])

In [19]:
linsys.relative_residual([1, 1])

---
## Solving Linear Systems

How can do something when we there are no solution for $Ax=b$? We can minimise $|| Ax - b ||$ to find an approximate solution.   

Let $x^{*}$ be a vector that minimises the squared sum of residuals $\lVert Ax - b \rVert^2$ i.e., for all $x \in \mathbb{R}^n$,

\begin{align}
\lVert Ax - b \rVert^2 \geq \lVert A x^{*} - b \rVert^2
\end{align}

We says that the vector $x^{*}$ is the **least-squares solution** to the linear system $Ax = b$.

<img src="figures/lecture-06/theorem-least-squares-solution.png" width="600" />

<img src="figures/lecture-06/least-squares-solution-derivation.png" width="600" />


The last equation is called the **Normal Equation**. The normal equation is about finding an orthogal projection that is in the range of $A$ since $b$ is not in the range of $A$. The range of $A$ is all the possible vectors that can created by the matrix $A$.

There is a geometric interpretation of least-squares solution:

<img src="figures/lecture-06/least-squares-solution-geometric.png" width="600" />


Notice that $b$ is not in the range of $A$. Basically, the Normal Equation performs an orthogonal projection of $b$ onto the subspace range of $A$.

---
## Least-Squares Problems

<img src="figures/lecture-06/example-12.1.png" width="600" />



Suppose $x_1$ represent the first type of concrete and $x_2$ represent the second. This problem can be formulated with the following linear equations:

$$
0.3 x_1 + 0.1 x_2 = 5 \\
0.4 x_1 + 0.2 x_2 = 3 \\
0.3 x_1 + 0.7 x_2 = 4
$$

In [20]:
def create_ex121():
    A = [[0.3, 0.1],
         [0.4, 0.2],
         [0.3, 0.7]]
    b = [5, 3, 4]
    return LinearSystem(A, b)
ex121 = create_ex121()
sol121 = ex121.least_squares_solution()
sol121

array([[2145/203],
       [195/203]])

In [21]:
utils.to_decimal(sol121)

---

## Example 12.1: Line Fitting

The least-squares analysis can also be used to find a straight line that best fit a set of experimental data. This is a useful tool that can be used when a system of equations is **inconsistent**. Suppose we have a problem that can represented as a set of three linear equations:
\begin{align}
3m + c &= 3 \\
3m + c &= 4 \\
4m + c &= 15
\end{align}
We would like to find a straight line given by:
\begin{align}
y = mt + c
\end{align}
The straight line that best fit the data points is the one that minimises:
$$
\lVert Ax - b \rVert^2
$$
Therefore, we can use least-squares solution on this problem.

In [22]:
def create_ex123():
    A = [[2, 1],
         [3, 1],
         [4, 1]]
    b = [3, 4, 15]
    return LinearSystem(A, b)
ex122 = create_ex123()

In [23]:
# Check whether the system is inconsistent
ex122.is_inconsistent()

True

In [24]:
ex122.least_squares_solution()

array([[6],
       [-32/3]])

Using the least-squares solution, we have found that the line that best fit the data points is described by:

\begin{align}
 y = 6t - \frac{32}{3}
\end{align}

A graphical illustration of our problem is shown in Figure 12.2:

<img src="figures/lecture-06/figure-12.2.png" width="600" />


---
## Polynomial Regression through Least Square Method 

We can also use the normal equation to fit data to other than a straight line. Consider the following data that looks like data whose graphs looks like a parabola:

| $x_i$ 	| $y_i$ 	|
|-----	|-----	|
| 1   	| 1   	|
| 2   	| 5   	|
| 3   	| 8   	|
| 4   	| 17  	|
| 5   	| 16  	|

A good fit to this data is to find $a$, $b$ and $c$ such that $y(x_i) = ax_i^2 + bx_i + c$ is closest to the data. In the least-squares sense, this means $y_i - y(x_i) = y_i - (ax^2 + bx_i + c)$

In [25]:
def create_parabola():
    A = [[1**2,  1,  1],
         [2**2,  2,  1],
         [3**2,  3,  1],
         [4**2,  4,  1],
         [5**2,  5,  1]]
    b = [1, 5, 8, 17, 26]
    return LinearSystem(A, b)
ex_parabola = create_parabola()
ls = ex_parabola.least_squares_solution()
ls

array([[8/7],
       [-23/35],
       [4/5]])

In [26]:
utils.to_decimal(ls)

The coefficients are:
$$
a = 1.1429, b=-0.6571, c=0.8
$$

---
Let us look at another example:

In [27]:
def create_parabola2():
    A = [[0.00,  0.00,  1],
         [0.25**2,  0.25,  1],
         [0.50**2,  0.50,  1],
         [0.75**2,  0.75,  1],
         [1.00**2,  1.00,  1]]
    b = [1.00, 1.2840, 1.6487, 2.1170, 2.7183]
    return LinearSystem(A, b)
ex_parabola2 = create_parabola2()
ls = ex_parabola2.least_squares_solution()
ls

array([[3691/4375],
       [18904/21875],
       [175899/175000]])

In [28]:
utils.to_decimal(ls)

The coefficients of the polynomial are:
$$
a = 0.8437, b=0.8642, c=1.0051
$$

---
## QR decomposition (not covered in the lecture)

QR decomposition is more efficient method than the normal equation method of solving a least squares problem. QR decomposition can be be used to solve problems like:
$$
\min_{x} \lVert A \boldsymbol{x} - b \rVert
$$


---
## Recursive Least-Squares (RLS) Algorithm

In Example 12.1, we are given a set of experimental points $\{ (t_0, y_0), (t_1, y_1), (t_2, y_2) \}$, and we find the parameters $m^{*}$ and $c^{*}$ of the straight line that best fits these data in the least-squares sense. Suppose that
we are now given an extra measurement point $(t_3, y_3)$, so that we now have a  set of four experimental data points. We need to update our line. There is two ways to solve this:

1. We can go through the procedure for finding the parameters of the line of best fit for this set of four points. 
2. We can use previous calculations of $m^{*}$ and $c^{*}$ for the three data points to calculate the parameters for the four data points. This is more efficient. In effect, we simply "update" our values of $m^{*}$ and $c^{*}$ to accommodate the new data point. 

The second procedure is called the recursive least-squares (RLS) algorithm.


<img src="figures/lecture-06/derive-rls-1.png" width="600" />




<img src="figures/lecture-06/derive-rls-2.png" width="600" />




<img src="figures/lecture-06/derive-rls-3.png" width="600" />




<img src="figures/lecture-06/derive-rls-4.png" width="600" />




<img src="figures/lecture-06/derive-rls-5.png" width="600" />




<img src="figures/lecture-06/derive-rls-6.png" width="600" />



where

<img src="figures/lecture-06/derive-rls-8.png" width="200" />



This algorithm works like the Kalman Filter


<img src="figures/lecture-06/derive-rls-7.png" width="600" />



--- 
## Example 12.6

<img src="figures/lecture-06/example-12.6-a.png" width="600" />




<img src="figures/lecture-06/example-12.6-b.png" width="600" />



<img src="figures/lecture-06/example-12.6-c.png" width="600" />



<img src="figures/lecture-06/example-12.6-d.png" width="600" />


---
## Solution to a Linear System with Minimum Norm


<img src="figures/lecture-06/linear-system-with-minimum-norm-problem.png" width="600" />




<img src="figures/lecture-06/linear-system-with-minimum-norm-solution.png" width="600" />



---
## Example 12.7

<img src="figures/lecture-06/example-12.7.png" width="600" />




In [29]:
def create_ex127():
    A = [[1, 2, -1],
         [4, 1,  3]]
    b = [1, 0]
    return LinearSystem(A, b)
ex127 = create_ex127()

In [30]:
solution127 = ex127.solve_minimum_norm()
solution127

array([[2/21],
       [1/3],
       [-5/21]])

In [31]:
utils.to_decimal(solution127)

---

## Kaczmarz's Algorithm


<img src="figures/lecture-06/kaczmarz-algorithm-intro.png" width="600" />


<img src="figures/lecture-06/kaczmarz-algorithm-1.png" width="600" />


<img src="figures/lecture-06/kaczmarz-algorithm-2.png" width="600" />


<img src="figures/lecture-06/kaczmarz-algorithm-3.png" width="600" />


<img src="figures/lecture-06/kaczmarz-convergence-theorem.png" width="600" />




---

## Moore-Penrose inverse




The Moore-Penrose inverse defines *pseudoinverse* or *generalised inverse* of a given matrix $A \in \mathbb{R}^{m \times n}$ which plays the role as $A^{-1}$ when $A$ does not have an inverse (e.g., when $A$ is not a square matrix or the determinant is zero). The Moore-Pensore inverse of a given matrix $A$ is denoted $A^{\dagger}$


<img src="figures/lecture-06/moore-penrose-inverse-problem.png" width="600" />

where $r \leq \min\{m,n\}$.

<img src="figures/lecture-06/moore-penrose-inverse-case-1.png" width="600" />


<img src="figures/lecture-06/moore-penrose-inverse-case-2.png" width="600" />
